## NLP

Understand basic NLP concepts and apply text preprocessing techniques.

In [1]:
import pandas as pd

data = {
    "text": [
        "I love machine learning!",
        "NLP is amazing and fun",
        "I hate bugs in code",
        "Debugging is very frustrating sometimes",
        "I enjoy learning new technologies"
    ]
}

df = pd.DataFrame(data)
df

                                      text
0                 I love machine learning!
1                   NLP is amazing and fun
2                      I hate bugs in code
3  Debugging is very frustrating sometimes
4        I enjoy learning new technologies

In [2]:
df["lower"] = df["text"].str.lower()
df

,text,lower
0,I love machine learning!,i love machine learning!
1,NLP is amazing and fun,nlp is amazing and fun
2,I hate bugs in code,i hate bugs in code
3,Debugging is very frustrating sometimes,debugging is very frustrating sometimes
4,I enjoy learning new technologies,i enjoy learning new technologies

**Tokenization**

In [3]:
import nltk
nltk.download('punkt')

from nltk.tokenize import word_tokenize

df["tokens"] = df["lower"].apply(word_tokenize)
df

[nltk_data] Downloading package punkt to /Users/apple/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

,text,lower,tokens
0,I love machine learning!,i love machine learning!,"[i, love, machine, learning, !]"
1,NLP is amazing and fun,nlp is amazing and fun,"[nlp, is, amazing, and, fun]"
2,I hate bugs in code,i hate bugs in code,"[i, hate, bugs, in, code]"
3,Debugging is very frustrating sometimes,debugging is very frustrating sometimes,"[debugging, is, very, frustrating, sometimes]"
4,I enjoy learning new technologies,i enjoy learning new technologies,"[i, enjoy, learning, new, technologies]"

**Remove Stopwords**

In [4]:
nltk.download('stopwords')

from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))

df["no_stopwords"] = df["tokens"].apply(
    lambda words: [word for word in words if word not in stop_words]
)

df

[nltk_data] Downloading package stopwords to /Users/apple/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

,text,lower,tokens,no_stopwords
0,I love machine learning!,i love machine learning!,"[i, love, machine, learning, !]","[love, machine, learning, !]"
1,NLP is amazing and fun,nlp is amazing and fun,"[nlp, is, amazing, and, fun]","[nlp, amazing, fun]"
2,I hate bugs in code,i hate bugs in code,"[i, hate, bugs, in, code]","[hate, bugs, code]"
3,Debugging is very frustrating sometimes,debugging is very frustrating sometimes,"[debugging, is, very, frustrating, sometimes]","[debugging, frustrating, sometimes]"
4,I enjoy learning new technologies,i enjoy learning new technologies,"[i, enjoy, learning, new, technologies]","[enjoy, learning, new, technologies]"

**Stemming**

In [5]:
from nltk.stem import PorterStemmer

stemmer = PorterStemmer()

df["stemmed"] = df["no_stopwords"].apply(
    lambda words: [stemmer.stem(word) for word in words]
)

df

,text,lower,tokens,no_stopwords,stemmed
0,I love machine learning!,i love machine learning!,"[i, love, machine, learning, !]","[love, machine, learning, !]","[love, machin, learn, !]"
1,NLP is amazing and fun,nlp is amazing and fun,"[nlp, is, amazing, and, fun]","[nlp, amazing, fun]","[nlp, amaz, fun]"
2,I hate bugs in code,i hate bugs in code,"[i, hate, bugs, in, code]","[hate, bugs, code]","[hate, bug, code]"
3,Debugging is very frustrating sometimes,debugging is very frustrating sometimes,"[debugging, is, very, frustrating, sometimes]","[debugging, frustrating, sometimes]","[debug, frustrat, sometim]"
4,I enjoy learning new technologies,i enjoy learning new technologies,"[i, enjoy, learning, new, technologies]","[enjoy, learning, new, technologies]","[enjoy, learn, new, technolog]"

**Lemmatization**

In [6]:
nltk.download('wordnet')

from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

df["lemmatized"] = df["no_stopwords"].apply(
    lambda words: [lemmatizer.lemmatize(word) for word in words]
)

df

[nltk_data] Downloading package wordnet to /Users/apple/nltk_data...

,text,lower,tokens,no_stopwords,stemmed,lemmatized
0,I love machine learning!,i love machine learning!,"[i, love, machine, learning, !]","[love, machine, learning, !]","[love, machin, learn, !]","[love, machine, learning, !]"
1,NLP is amazing and fun,nlp is amazing and fun,"[nlp, is, amazing, and, fun]","[nlp, amazing, fun]","[nlp, amaz, fun]","[nlp, amazing, fun]"
2,I hate bugs in code,i hate bugs in code,"[i, hate, bugs, in, code]","[hate, bugs, code]","[hate, bug, code]","[hate, bug, code]"
3,Debugging is very frustrating sometimes,debugging is very frustrating sometimes,"[debugging, is, very, frustrating, sometimes]","[debugging, frustrating, sometimes]","[debug, frustrat, sometim]","[debugging, frustrating, sometimes]"
4,I enjoy learning new technologies,i enjoy learning new technologies,"[i, enjoy, learning, new, technologies]","[enjoy, learning, new, technologies]","[enjoy, learn, new, technolog]","[enjoy, learning, new, technology]"

In [7]:
df["clean_text"] = df["lemmatized"].apply(lambda words: " ".join(words))
df

,text,lower,tokens,no_stopwords,stemmed,lemmatized,clean_text
0,I love machine learning!,i love machine learning!,"[i, love, machine, learning, !]","[love, machine, learning, !]","[love, machin, learn, !]","[love, machine, learning, !]",love machine learning !
1,NLP is amazing and fun,nlp is amazing and fun,"[nlp, is, amazing, and, fun]","[nlp, amazing, fun]","[nlp, amaz, fun]","[nlp, amazing, fun]",nlp amazing fun
2,I hate bugs in code,i hate bugs in code,"[i, hate, bugs, in, code]","[hate, bugs, code]","[hate, bug, code]","[hate, bug, code]",hate bug code
3,Debugging is very frustrating sometimes,debugging is very frustrating sometimes,"[debugging, is, very, frustrating, sometimes]","[debugging, frustrating, sometimes]","[debug, frustrat, sometim]","[debugging, frustrating, sometimes]",debugging frustrating sometimes
4,I enjoy learning new technologies,i enjoy learning new technologies,"[i, enjoy, learning, new, technologies]","[enjoy, learning, new, technologies]","[enjoy, learn, new, technolog]","[enjoy, learning, new, technology]",enjoy learning new technology